<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>SyntaxCircus.Blazor.Components</PackageId>
    <Title>SyntaxCircus Blazor Components</Title>
    <Description>UI/CSS-framework-agnostic components for Blazor applications.</Description>
    <Authors>Syntax Circus LLC</Authors>
    <Company>Syntax Circus LLC</Company>
    <Copyright>Copyright © Syntax Circus LLC</Copyright>
    <PackageTags>blazor;components;razor;not-found;404</PackageTags>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/Syntax-Circus/SyntaxCircus.Blazor.Components</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Syntax-Circus/SyntaxCircus.Blazor.Components</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="GitVersion.MsBuild" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
